In [16]:
import pandas as pd
pd.set_option("display.max_rows", 1000)

In [70]:
from preprocess import load_data

data = load_data()

data.keys()

dict_keys(['course_chapter_items', 'courses', 'subgroups', 'test_seen', 'test_seen_group', 'test_unseen', 'test_unseen_group', 'train', 'train_group', 'users', 'val_seen', 'val_seen_group', 'val_unseen', 'val_unseen_group'])

In [4]:
data['courses'].iloc[0:1]

,course_id,course_name,course_price,teacher_id,teacher_intro,groups,sub_groups,topics,course_published_at_local,description,will_learn,required_tools,recommended_background,target_group
0,61888e868f154b000781b45a,少女人妻華麗變身：七大妝容七彩的夢幻樂園,1800,61888e7bb7fe1c0006850eff,在美妝 KOL 圈裡屬個人風格強烈的 Alice，在清新與叛逆風格間遊刃有餘，其幽默的美妝影...,生活品味,"更多生活品味,護膚保養與化妝","更多生活品味,護膚保養與化妝",NaN,"<img src=""https://images.api.hahow.in/images/6...",不再害怕各種顏色的彩妝，可以更隨心搭配各種繽紛的顏色。\n,所需工具為：視課程實際會用到的彩妝用品,只要你有一顆愛化妝、想變漂亮的心皆可以參加。\n\n⚠️ 雖然課程當中會帶到相關彩妝技巧，不...,熱愛彩妝的人

In [5]:
data['users'].iloc[0:1]

,user_id,gender,occupation_titles,interests,recreation_names
0,54ccaa73a784960a00948687,female,NaN,"職場技能_創業,藝術_電腦繪圖,設計_介面設計,設計_動態設計,設計_平面設計,投資理財_投...",NaN

### process courses

In [6]:
data['train'].iloc[1]['course_id']

'5bfd47782d018e0020e4b0e4 5fc4a352d375951a03cc0d45 6090dda489d06d6a564c9a78 5fd9b1ce0fb8aa8b32928d5b 6030c9cd99e14cc2401e66b9 5cad79b0d133060020f44c5e 5f1f9092673f8866bf9604af 5f59ff38f24eac1485f8097f 607015a2db27b36747727e80'

In [7]:
data['train'].query("user_id == '56dae2b74e3ef90900b7bd0e'")

,user_id,course_id
31292,56dae2b74e3ef90900b7bd0e,5fc5ee1b08b74a6e3723abd2 6059aee039f2512548c18...

In [8]:
data['val_unseen']

,user_id,course_id
0,612c1fcd560d8100069aa5ba,5f14aeabcad0d0afe5ea3898 60ac8e42992b7aadf9d019d8
1,558b954c6dec460f00111131,5fc5ed671be929537e5283bb 5fc5edae001c9102feab8...
2,591de47900f58c070078cd99,60aeac37bca91777bf5bb114
3,612e5ebd31e50c0006fc4611,5fc5ee1b08b74a6e3723abd2 60cb0a440dabda80019d5...
4,60c248c62757c16af6160429,60a49d7c62c6aea8d38e3903
...,...,...
11617,617eb7aff2c5f00006592046,6030c9cd99e14cc2401e66b9 5fc5ee1b08b74a6e3723a...
11618,613253cdd5d02a0007225fe4,5e8e9d3c5a140c3d1e1c5245
11619,617eb70db23194000781f7cf,61381a3f33a3960006df1eb3
11620,5c9f3af172a72f0021508a87,5ce3a183138a45002046859d
11621,614822bd2cdf770007533c19,6155cda6d425f500065f5c96

In [10]:
data['train']['course_id'] = data['train']['course_id'].apply(lambda s: s.split())

In [11]:
train_df = data['train'].explode("course_id")

In [12]:
courses = sum(data['val_unseen'].course_id.apply(lambda s: s.split()).to_list(), [])

In [13]:
len(courses)

19618

In [14]:
df_tmp = data['courses'].merge(df, on=["course_id"], indicator = True, how='left').loc[lambda x : x['_merge']!='both']

NameError: name 'df' is not defined

In [15]:
train_df.groupby("course_id").count()

                          user_id
course_id
54d5a117065a7e0e00725ac0       60
54d5d9952246e60a009ec571       11
54d7148a2246e60a009ec588       55
54f1268f4ec3c809002e4a29       23
551171a938239d1000577864       13
...                           ...
60f83c44b355920006abbd3f       54
60fa9c7d1917300007734fd3       86
60ffeb101f74d40006fe3fd8        8
61034f3d4ef8b500067afc1c       82
611287c9c7a95900068fc994       11

[664 rows x 1 columns]

In [185]:
data['val_unseen'].course_id.apply(lambda s: s.split()).explode()

0        5f14aeabcad0d0afe5ea3898
0        60ac8e42992b7aadf9d019d8
1        5fc5ed671be929537e5283bb
1        5fc5edae001c9102feab8ecf
1        5e55f57bc8bfb600249406e1
                   ...
11617    5ef099ab678184065fd4d426
11618    5e8e9d3c5a140c3d1e1c5245
11619    61381a3f33a3960006df1eb3
11620    5ce3a183138a45002046859d
11621    6155cda6d425f500065f5c96
Name: course_id, Length: 19618, dtype: object

In [17]:
pd.to_datetime(data['courses'].course_published_at_local).max()

Timestamp('2022-03-29 12:00:16.763000')

In [18]:
pd.to_datetime(data['courses'].merge(data['val_seen'].course_id.apply(lambda s: s.split()).explode(), on=["course_id"], how="inner")["course_published_at_local"]).max()

Timestamp('2022-01-27 12:02:16.752000')

In [19]:
pd.to_datetime(data['courses'].course_published_at_local).max()

Timestamp('2022-03-29 12:00:16.763000')

In [161]:
data['courses'].groupby(["teacher_id", "course_id"]).agg(n=("course_id", "count")).sort_values("n").reset_index().merge(train_df.groupby("course_id").count(), on=["course_id"], how="left").fillna(0).set_index(["teacher_id", "course_id"]).sort_index()

                                                   n  user_id
teacher_id               course_id
54cb5c2ea784960a00948678 54d5d9952246e60a009ec571  1     11.0
54d5a079065a7e0e00725abe 54d5a117065a7e0e00725ac0  1     60.0
54d713532246e60a009ec586 54d7148a2246e60a009ec588  1     55.0
54de6f88dbc18009004c1605 54f1268f4ec3c809002e4a29  1     23.0
54e4b5fbc5c9c00900cd8d4c 59b8a97dcd5792070055ef75  1    291.0
54f5c694e977de0a00d46a06 551171a938239d1000577864  1     13.0
54f810e200a1420f0068283a 5593f992cfe8320b00ccd4c4  1     27.0
54fe479ab27eaa0b0024edd1 5f506991b1b6d678526889e1  1     25.0
5511977138239d100057786e 551198a738239d1000577870  1     32.0
5513e92438239d10005778df 5513e92b38239d10005778e1  1     39.0
5514db1438239d1000577911 551a6be023774e0a001eb20c  1     24.0
55263e312408170a00422fcb 5d77176845639e00212bc562  1    114.0
55307ad9d530a90a00a3a88f 55307d94d530a90a00a3a896  1      7.0
55386d41d530a90a00a3a9d5 556ad58777a8710900bedffe  1     33.0
555367c49d3a25090000072f 557ad62bd736230f00adb2ab  1     18.0
5555ed8d2b07e80e00b1088d 568537d0e8ff9b20003cf504  1      0.0
55599679dfe21b0a00e776d7 55599687dfe21b0a00e776d9  1      5.0
558a6d366dec460f00111098 5591501e6dec460f00111314  1     31.0
5593a25dcfe8320b00ccd4af 559a217dcfe8320b00ccd75b  1      6.0
559e49105850311000fca503 559e49185850311000fca504  1    124.0
55a4c48a7b4d991000119570 5615f2b40eb66b0a00f16f6b  1     65.0
55a4cb297b4d99100011957c 55a4d6397b4d99100011957d  1     11.0
55ae202e7b4d9910001198f1 55ae208a7b4d9910001198f2  1     19.0
55ae33ee7b4d99100011990c 55ae34247b4d99100011990d  1      1.0
                         55ae36c87b4d99100011990f  1      1.0
                         55ae66017b4d991000119959  1      0.0
55b0ba1e7b4d991000119a91 55b0ba667b4d991000119a92  1      1.0
55c634cf7b4d99100011a4a9 55c636d27b4d99100011a4aa  1     21.0
                         5b14b696865ad2001ec2f7ae  1      7.0
55c80c187b4d99100011a4f4 55e66f33fa223d100058f5f7  1     44.0
55d6c7eafe5f710a00ac7aa1 55ea1ea8fa223d100058f7df  1    111.0
                         5864e19cf108e00800c24f7a  1     14.0
55e00e4afa223d100058f141 55e66307fa223d100058f5c9  1      8.0
                         55e6664ffa223d100058f5d6  1     12.0
                         55e670d2fa223d100058f5ff  1     18.0
                         592bde032f29aa0700af81ae  1     33.0
55e3dcb4fa223d100058f3ca 55e3dccbfa223d100058f3cb  1     20.0
                         5606262ac61d930a00455fad  1     15.0
55e7f6d1fa223d100058f6da 55e82d8efa223d100058f6f4  1     52.0
55eb1c12fa223d100058f82f 57976e0dd0c3030700419d8b  1     45.0
55ee86a2fa223d100058f948 563c8763423bdd0a00104555  1    112.0
                         58abfb2f5c4e6507007c2b46  1     82.0
55fe3d0c160d9810000898b2 57c6960f61d9350700e6cff5  1     30.0
55fe931b160d9810000898ff 5c39713cf699690021a0fba2  1     58.0
5608260ec61d930a00456138 56082612c61d930a00456139  1      1.0
56189df7df7b3d0b005c6638 56189df9df7b3d0b005c6639  1    907.0
                         586fae97a8aae907000ce721  1    372.0
                         5d1ba52a0d5f3b0021dbb996  1    178.0
56385f48423bdd0a00103c3b 56385f4e423bdd0a00103c3c  1     69.0
                         5670dae013ef621200899e68  1     91.0
                         56f521864e3ef90900b82c12  1     51.0
                         57dd2673d5766a0700c6be33  1     37.0
                         5bb7142de6ed7e001e02af68  1    138.0
56389455423bdd0a00103c4e 5638945e423bdd0a00103c4f  1     15.0
5639fe0f423bdd0a00103d54 5639fe25423bdd0a00103d55  1     31.0
563ab2fa423bdd0a00103dd6 563ab301423bdd0a00103dd7  1     32.0
563b5479423bdd0a00103e8f 563b54ff423bdd0a00103e90  1     37.0
563ea997423bdd0a001047ec 563ea99a423bdd0a001047ed  1      9.0
56402c6a423bdd0a00104992 56402c70423bdd0a00104993  1     43.0
564818be42ee8d100033a022 56c81f37182fba0e00c69d53  1     10.0
56496a6f42ee8d100033a0d6 56499b1542ee8d100033a0fa  1    138.0
                         595dac43bbc89b07008609ac  1     32.0
564b944942ee8d100033a215 564b945342ee8d100033a216  1    129.0
565e6b1636328c10000aaba9 591d96d300f58c070078c4c6  1     21.0
565f3ecf36328c10000aac52 5697dfb64ec4c609007d1b5f  1      7.0
56683e965f4374480075cb61 566985d25f4374480075cc85  1     36.0
566bae4713ef6212008998c1 57e00e5ad5766a0700c6d80d  1     71.0
566e1ea113ef621200899ab9 5e34cc8550c9ee0024df5297  1    135.0
567787f950562140005e6776 567b85a350562140005e6b86  1     72.0
                         57611649f1399b0900e22e31  1     11.0
567f532150562140005e6e6b 567f6b1350562140005e6e86  1     36.0
                         568552e0e8ff9b20003cf518  1    128.0
56810fd750562140005e6fcd 56810fdd50562140005e6fce  1     17.0
568a1d73e8ff9b20003cf8f3 595cd372bbc89b07008603a2  1     14.0
568cd519e8ff9b20003d009e 569110e6e8ff9b20003d0cbd  1     40.0
568e663fe8ff9b20003d0780 5c03c32ea45e4500200f07a2  1     10.0
5698b33a4ec4c609007d1c46 594a48b50e64510700b6f2ee  1     18.0
569cf0b74ec4c609007d231b 56a3ace74ec4c609007d3065  1      9.0
56a083354ec4c609007d2964 56c1e3b3e91d590900234105  1     62.0
56a1be974ec4c609007d2c6b 56a1e0164ec4c609007d2cb0  1     62.0
56befc96c36f680900ced168 5e89782859e0250022940c6d  1     10.0
56c2ceb6182fba0e00c68f8f 56d68e0b182fba0e00c6d9d7  1     15.0
56cd088d182fba0e00c6b5af 579dc01ed0c303070041c13c  1     32.0
56ce9716182fba0e00c6c0a1 56ce9b4f182fba0e00c6c0c1  1     44.0
56cea30e182fba0e00c6c0ef 56e0e9fb4e3ef90900b7cff1  1      0.0
56d57f4d182fba0e00c6d71a 5737f2acfad4ef0a006b6912  1    161.0
56d68012182fba0e00c6d9b1 56d68017182fba0e00c6d9b2  1     48.0
56d70783182fba0e00c6dbb6 5788984dd0c303070041573a  1     31.0
56d7a23b182fba0e00c6dc77 56d7a243182fba0e00c6dc78  1    412.0
                         5b8cd7873aeadb001e5da117  1    154.0
56d7e2e4182fba0e00c6dd4d 56eff6174e3ef90900b808a3  1      8.0
56d7fbf7182fba0e00c6dd81 56de29dc4e3ef90900b7c649  1    212.0
56e2a3eb4e3ef90900b7d6c9 56e2a43b4e3ef90900b7d6cd  1    276.0
                         56feb1ac2ba01d09002bbb8e  1    107.0
56e3d9404e3ef90900b7db77 6079a317d9f5eab97ac3203b  1    412.0
56e8be814e3ef90900b7ef6a 56f503104e3ef90900b82b94  1     30.0
                         5858badef528320700f8c04a  1     24.0
56ef73344e3ef90900b8061c 5892e48a5f188a07007f7013  1    220.0
                         59ae5da5cd5792070055b973  1    190.0
56f0d9534e3ef90900b80ccd 58d5c70c27ea7d070060160e  1    456.0
56f274bd4e3ef90900b81bc3 570dfc3b7192420900a0009f  1     15.0
                         5c91f4cc1a3ca1002005746b  1      5.0
56f8809a4e3ef90900b83503 56fcdc8f2ba01d09002bb266  1     95.0
                         5930dd1922a4f20700df14fc  1    162.0
56f8997c4e3ef90900b83543 5ee0087e1824f260e1a311d6  1     43.0
56f91e832ba01d09002ba80d 56fbd6112ba01d09002bae64  1      3.0
56fe99652ba01d09002bbb3e 571475dc234ded0a00a40d56  1     20.0
570109c62ba01d09002bc0ce 570109d32ba01d09002bc0cf  1    185.0
570e7d5e7192420900a00494 57184c0c234ded0a00a41c31  1    182.0
                         59a575d0cd5792070055766f  1    103.0
                         5c7f583deb710500203b37f1  1     33.0
5719ab9d234ded0a00a42357 5b9f4af8ca498a001e91fb3c  1    177.0
571de47dd60bb30900917ea5 5b3cdd6ed03140001eebeadc  1     95.0
572abc76d60bb3090091cc9c 61161afbbeafad00060b4503  1      0.0
572be497d60bb3090091d206 572be49fd60bb3090091d208  1    284.0
                         59cdbd0d86e624001ee63186  1    413.0
                         5af3b86db44939001e465160  1    356.0
                         5c8b58b5669d56001f348f69  1    149.0
                         5fb5fdd083afa949558a7d88  1   1490.0
5730a8a8b2a279090045f106 5a32a1c6a99031007d977e9d  1     34.0
57312cf7b2a279090045fc19 57486a9f0a2f5c0900c97205  1     23.0
                         5ee4d65789dc7e4854909ba1  1   1415.0
57313363b2a279090045fca1 598c2c8ab987ea0700cea684  1    221.0
                         5a2659df603553001e3d2919  1     74.0
                         5c18f9c611b27900205c9ff5  1     14.0
                         5ca2cee872a72f0021514421  1     93.0
                         5eaf7eec3e47cfd04f222519  1    113.0
5733583efad4ef0a006b2a36 5d5aac6e8e9eb60021211902  1    155.0
                         5f194354cad0d086f3ee24cf  1    155.0
5733873dfad4ef0a006b2cb2 5e9e7c78735b0146e5cbae8b  1     11.0
5733d550fad4ef0a006b2dfb 57972592d0c3030700419c32  1     72.0
573a6c7dfad4ef0a006b8b42 5bab74d99afd5e009d88a0ad  1     62.0
573d7d33fad4ef0a006bb3fc 59d61b0d1f6685001ee6a2bb  1      3.0
57401daefad4ef0a006bc8c1 57424af9fad4ef0a006bdb40  1     83.0
575045e0206cd60900c53084 575045e7206cd60900c53085  1    117.0
5755836bcb768f0900cd3e04 5a6f15aee77921001e624ee9  1     68.0
575649accb768f0900cd4fe4 5e9c1b4874efbcdcf23a6471  1    159.0
575c4335f1399b0900e20ec2 5e8ed2a0939c7870e53f2cad  1    137.0
575e544bf1399b0900e2196a 5de7148a46da740021ec240a  1    145.0
575fe866f1399b0900e22553 5b33cd4f2c4c44004391c836  1     25.0
57601586f1399b0900e22759 576015bbf1399b0900e2275a  1      8.0
57638162f1399b0900e23d70 57638167f1399b0900e23d71  1      3.0
5763a7e5f1399b0900e23f39 5763a7ecf1399b0900e23f3a  1     32.0
57679593f1399b0900e25503 5a3bc9bf110d8c001e577e75  1     35.0
5772308cc2917a110075f93b 57728810c2917a110075fb68  1    112.0
                         589fe5035f188a07007fd5b2  1     48.0
5772b50cc2917a110075fcf8 5772b51ec2917a110075fcf9  1     36.0
5772c850c2917a110075fd21 578dc4b1d0c30307004170af  1     20.0
                         578dd474d0c303070041711a  1     76.0
577914ce3b80e50700c26f0f 5c9390c0938233001f8b72e9  1     32.0
                         5ebc0e34df21684ebcd7637b  1     26.0
577d94c3d0c3030700411733 577d9599d0c303070041173a  1    303.0
                         596f61cfede9500700e6ced2  1     70.0
5780d61cd0c3030700412eeb 5780d82fd0c3030700412ef1  1     39.0
57826469d0c3030700413698 5b37acf5b804e6001efe761b  1    105.0
578ce210d0c3030700416c38 578ce3ced0c3030700416c46  1     20.0
578db7efd0c303070041703c 585eb576f108e00800c21f76  1    189.0
                         5a5230b5fa1e3f001e8d93da  1    105.0
57999d76d0c303070041a99d 57999d81d0c303070041a99e  1     19.0
579b33efd0c303070041b2de 5de5da98adb04100214d6e08  1    146.0
579ded05d0c303070041c22d 57b83c50c7425c0700c6921f  1     37.0
57a3034bd0c303070041dc32 57a30629d0c303070041dc4b  1      7.0
57a80583aecc5c07000976ba 6031136edd9bc1681035b892  1    256.0
57a9f0bbaecc5c0700099103 57bc8be49ab5080700399c1c  1     40.0
57aae35585b09707004202fe 57c01f0b9ab508070039b62c  1      1.0
57af48c106665507002de0c4 5ca16d2972a72f002150e9b2  1     24.0
57b727b0c7425c0700c68c86 57bc2b219ab5080700399866  1      4.0
57b908d4c7425c0700c695b3 57b90a00c7425c0700c695b8  1      8.0
57c7d71561d9350700e6d96d 57c7d75c61d9350700e6d972  1     23.0
57ccc02b61d9350700e7143b 58a00f865f188a07007fd709  1    342.0
                         59b0dd09cd5792070055c99a  1    246.0
57d20956ed63880700d9fa96 57d60701ed63880700da234c  1     13.0
57dacf94d5766a0700c6ae9a 57dacfa5d5766a0700c6ae9c  1     34.0
                         594007f6d0472a0700f268b3  1     21.0
                         5f76847349fac446f5494e20  1     71.0
57de2c73d5766a0700c6c520 57e8bf56a69c240700069d45  1    293.0
57e0ad9fd5766a0700c6d9f2 5c553fc779f1990022df773e  1      4.0
57e1e654d5766a0700c6e33a 5f75d45349fac4947b486454  1    183.0
57fc6339da04300700fdc7e2 5832a096aed2140700864309  1    120.0
580f15e0da04300700fe7f4a 580f1cedda04300700fe7fc9  1     12.0
                         586ec677a8aae907000cdd6f  1    458.0
5816e653cca88007007023da 581c3a59cca880070070561b  1     56.0
5818b103cca880070070368a 5ce99ccdea2d0500209afca2  1     63.0
5819b205cca8800700703d5c 60bdbc454ee6592acad8e950  1      0.0
581b3d17cca8800700704d2d 582870e05910c80700827db8  1      8.0
582341215910c807008259dc 5b928456de22ba001ee8e941  1     53.0
582541e55910c80700826797 582548cf5910c807008267b4  1      7.0
582aebfd9304bf0700078159 5cd8f375a4d3eb0020517eb1  1     17.0
5832c01baed21407008643c2 58358d5ef8325508002f96bb  1     16.0
58483fa0d821b10700a85869 58484022d821b10700a8586e  1     50.0
                         5f589d0dfa2fe10a49d66aea  1     25.0
584f9543d821b10700a88124 58578cf8f528320700f8baa6  1     32.0
584f9933d821b10700a88147 60aeac37bca91777bf5bb114  1     73.0
585a1ce2f528320700f8c728 58edb2824909c907004aa38b  1      7.0
585aa756dec3cf0700ec9d4c 598b01e6891876070047423a  1      5.0
586393b2f108e00800c24534 5bde82a4fec01400216660b9  1     17.0
58650351f108e00800c2507f 58677d39f108e00800c25f36  1     18.0
                         586a2519f108e00800c26e61  1      3.0
                         58bfdaab5c4e6507007cdeca  1      0.0
586f52a7a8aae907000ce37f 588732a75f188a07007f1cbc  1     14.0
58744a86a8aae907000d0684 58744feda8aae907000d06c0  1     61.0
587b5c156ecf3a0700b75da1 5f6ae6cd26d2a59589f9d069  1     86.0
587f295d6ecf3a0700b77d3d 587f29666ecf3a0700b77d40  1     34.0
5880cd966ecf3a0700b78cde 591a80571aa4b60f00364020  1     24.0
5899f0675f188a07007facc5 5c933df03c7b2c0020b2e6ce  1      6.0
58a105765f188a07007fdd9e 5d428e522fb50200206226e9  1      9.0
                         5f58478c880fc4310780cd8f  1     56.0
58aedee85c4e6507007c4595 58aedfd95c4e6507007c4599  1    196.0
                         5abe43287997a2001e7c0e01  1     40.0
                         5e55f57bc8bfb600249406e1  1   1061.0
                         607280245075a45ba6da6b5c  1    871.0
58af213e5c4e6507007c48f6 58af266c5c4e6507007c492a  1     54.0
                         5b1dfba5567cc1001e40c665  1     11.0
58c0237b5c4e6507007ce2c6 594f29d013cd380700228e7d  1    159.0
                         59849fbcacc1370700075d44  1     72.0
                         5c176b8411b27900205c5709  1    141.0
58c686beda45810700e512a4 5c5d46c879f1990022e068bb  1     37.0
58c6aea9da45810700e5140b 58cb3438da45810700e53507  1    108.0
58c6d497da45810700e5156a 58ca97dada45810700e53205  1    947.0
58ce73a4da45810700e5487e 5a2a6b3fa6501f001e2e9e86  1     20.0
58d21a7827ea7d07005fffbb 58d21b6c27ea7d07005fffc1  1    136.0
                         5b2af94aaef93c001e5ea939  1     80.0
58d3818027ea7d0700600912 58d46b4a27ea7d0700600e15  1     10.0
58d6269727ea7d07006017fe 58d6275727ea7d0700601804  1     40.0
58e5d4304909c907004a6574 58e5d4844909c907004a657a  1    273.0
                         5b6c498c19937f001e0a8e4f  1     54.0
58f34fa04909c907004ac6d1 597df7e2acc137070007013c  1    116.0
                         59c688e3757b61001eea421f  1     98.0
59049b49b684bf0700ec7255 59eca771ed6610001e82f778  1      3.0
5905b44eb684bf0700ec788c 5905b47ab684bf0700ec788d  1     25.0
59127a172fa2a607008bb718 593a0a69d0472a0700f24243  1      5.0
5917f52c2fa2a607008be7ee 5a2e3baea6501f001e2eb5eb  1    443.0
                         5c2417a649b19c002047e937  1    280.0
                         617a0a057bb91d0007a646d4  1      0.0
5919c6c01aa4b60f003632a6 5b1d3e30567cc1001e40ba13  1     39.0
                         5b2c8d3a2c4c440043912ceb  1     20.0
591c2ef700f58c0700787fc0 591c480a00f58c0700788178  1      8.0
591c78a300f58c07007890ad 592050350a6dcf0700ff3841  1    144.0
592159094781880700a4ac17 5bd43b15029bec001e0a4ba1  1      9.0
                         60a66f350297223a0f0af3fe  1     44.0
592e44c72f29aa0700af933d 592e5e5a2f29aa0700af943b  1     72.0
593c2dc0d0472a0700f24e9d 594cdd6813cd3807002283a9  1    145.0
                         5a954fb9702458001eb70ff5  1     98.0
5947c852d0472a0700f2add7 5947c8b3d0472a0700f2adda  1     35.0
                         5bd9339ea8f170002094b26a  1     46.0
                         5ea7da19bb90a4bffd4c71fe  1     51.0
5950fda213cd38070022af83 5aced6bad21aee001e55e63a  1    240.0
595c7bc5bbc89b070085ffa1 5ccfefa433f488001f7009f3  1     45.0
595f53dbede9500700e614fa 595f5423ede9500700e614fc  1      9.0
595fab93ede9500700e61843 5965e326ede9500700e66202  1      2.0
596b70a9ede9500700e69e0d 596b7241ede9500700e69e21  1    602.0
                         5abc57af7997a2001e7bde43  1     70.0
596ffcad9274560700553fb9 5e95c5b8845c8bf74c0102df  1    155.0
59718589ea17a30700d3968a 5972dda3ea17a30700d3a0a1  1      9.0
597d4fe4acc137070006f5df 61a5d89b3b954c0007022c77  1      0.0
5980539facc1370700071867 598053e0acc137070007186a  1    380.0
                         5eb657d7df2168001ad29aba  1     86.0
5989694eefb80b070005562e 598969a3efb80b0700055630  1     57.0
599744c2e6f91a07009fc8a0 602cfca1ea491d503578f99f  1     78.0
59a4e214cd57920700556f11 59af8ba6cd5792070055c074  1    214.0
                         5a87973ca52e3f001eeb6cd6  1    137.0
59a571bacd5792070055763f 59a95ed6cd57920700559676  1     29.0
59a6bbcacd57920700558226 59a6bf9bcd57920700558277  1     25.0
59a7c873cd57920700558c12 59c1c8c84c36510700f925b2  1     38.0
                         5aaf2dad1e4ee6001e9632fd  1     18.0
                         5cac9bd2d133060020f42ab4  1     45.0
                         5cee252cea2d0500209c0b8e  1     15.0
                         5d80dde645639e00212d81a5  1     22.0
                         5dff3b91f066100021955305  1     14.0
                         5ebce244df2168d2c1d83995  1     22.0
59b2b87ecd5792070055d5b6 5a671c0a85b4c2001eb80ca1  1    227.0
59b2bc32cd5792070055d5d5 59f1ea744b1842001e21b7c7  1     28.0
59ca211d01875f001e14b464 59fc084fa77a2d001eea9286  1     49.0
                         5bd6cafa2febb1001e900594  1      8.0
59dba94a1f6685001ee6bf7b 59eca796ed6610001e82f784  1     64.0
59df1d3742648c001e82dcee 59fbcb50a77a2d001eea9155  1     47.0
59e59309575ca6001eb94193 60b49deac0bb3035f1a6f885  1   1519.0
59e5f407c185e5001ef4cb02 5b6adb26715919001e50fb0f  1    154.0
                         5e4237b75b02f60024599973  1    582.0
59e851faef1581001e5c9880 59eaaaa5ed6610001e82e1ba  1     63.0
                         5a531b7d5518aa001e320c8c  1      1.0
59ef2edc4b1842001e21a49e 59fd188aa77a2d001eea9650  1    165.0
59f57c09e8c1dd001e90a907 59f57c88e8c1dd001e90a90b  1     34.0
59f97ae4a77a2d001eea8500 59f97b57a77a2d001eea8504  1     27.0
59fbd0daa77a2d001eea917a 5a7baad0b6ba47006f5660f0  1     47.0
                         5ba336da6971da001ea5ba53  1     27.0
5a083175bc13ad001ed9954e 5a0a6c87a15b3f001e9829b9  1    286.0
5a0b9734a15b3f001e983d19 5a0be0f7a15b3f001e9842ec  1     13.0
5a0bb5e0a15b3f001e983f9d 5ebb8bd7ba79d95ae6f18ba2  1     27.0
5a1250ec329456001e7aa2d5 5a12b299152204001e1bd488  1     45.0
5a1cf00a16b785001ed44e53 5a1cf54016b785001ed44e79  1     37.0
5a1f79a33e33cf001eae1e64 5a1f79ab3e33cf001eae1e66  1     20.0
                         5a1fd1b7e711cc001ede7a2d  1     25.0
                         5c1404fe11b27900205beea2  1     26.0
5a211434a6d4a5001ec3120e 5a211b15a6d4a5001ec31247  1    285.0
                         5a4dfd25fa1e3f001e8d6a35  1    143.0
5a2170bda6d4a5001ec3148b 5a2170d5a6d4a5001ec3148d  1    856.0
                         5b875e55297df5001efb869d  1    398.0
                         5b9d3a6dca498a001e917383  1    342.0
5a30ecaea99031007d976e65 5a30f238a99031007d976ebe  1     54.0
5a34f556c0cfff00e2c666a1 5a3669c5c0cfff00e2c670a1  1      8.0
5a3e1500ea647c008cf13148 5a4258c55c4d70001e866274  1    175.0
                         602bb8742225045c9d1d514c  1    241.0
5a4d005efa1e3f001e8d58c5 5a4f95a4fa1e3f001e8d81cd  1     43.0
5a523ba4fa1e3f001e8d946e 5c8e0a0a8d1cc80020951f1a  1    150.0
5a536a3c5518aa001e320f55 5a536d335518aa001e320f7c  1     57.0
                         601e5acb1b88f7481d7a05af  1     54.0
5a537f715518aa001e321073 5b8a4d1d3aeadb001e5cf364  1     17.0
5a5d98b8a97499001e463fd3 5a91379a44a1e4001eee5d8e  1     44.0
5a5fa0b16a444a0068d4d66f 5a6ed74fe77921001e624cfb  1      5.0
5a617e736a444a0068d4f392 5a6180016a444a0068d4f3aa  1    142.0
                         5d12e5ecac23d80020ad4bb3  1     82.0
5a634bb185b4c2001eb7f793 5f8426f5e4a0b485bcb8ac4e  1     48.0
5a6b7b183896c1001e4696e9 5eb0ce6f94c64edd52ba572b  1    131.0
5a7ae632b6ba47006f565d07 5a7ae6c7b6ba47006f565d09  1     36.0
5a8430a8a52e3f001eeb5ae5 5ac617cd7997a2001e7ca69c  1     41.0
                         5cc0f183f22cad0020777339  1     18.0
5a8d691847536b001e6348ec 5e46b7f85b02f600245ade9b  1    404.0
5a912d2044a1e4001eee5d42 5bb4bd2fe6ed7e001e01db23  1     22.0
                         5d5a2c1a7d4d7c00217effe4  1     38.0
5a93c4d418b67a001ee39779 5cad79b0d133060020f44c5e  1    357.0

In [191]:
from datetime import datetime

In [131]:
data['val_unseen'].course_id.apply(lambda s: s.split()).explode().to_frame("course_id").groupby("course_id").agg(n=("course_id", "count")).merge(df_tmp, on=["course_id"]).sort_values("n_x")

,course_id,n_x,course_name,course_price,teacher_id,teacher_intro,groups,sub_groups,topics,course_published_at_local,description,will_learn,required_tools,recommended_background,target_group,n_y,_merge
0,58bfdaab5c4e6507007cdeca,1,APP Inventor 2 進階實戰,1000,58650351f108e00800c2507f,行動創客學院 執行長\n長庚大學EMBA兼任助理教授\n師大附中自造實驗室諮詢委員,程式,手機程式開發,App inventor,2017-06-02 16:15:53.234,<h4>「五分鐘程式設計」系列又來囉！</h4><p>107年開始程式設計正式納入課綱，國、...,課程設計是從基礎出發並重視實作，除了能學到各種安卓手機硬體元件基本知識（例如：加速度、指南針...,1. Windows XP或以上/Mac OS（講師將使用 Mac OS）\n2. Chro...,不用對程式設計有經驗，只要有興趣，有一顆熱情學習的心即適合本課程。若有其它任一程式學習經驗更...,1. 希望從零開始學程式\n2. 玩Arduino硬體，並想透過APP遠端控制\n3. 希望...,NaN,left_only
19,611dbe96be4b2d000699b345,1,小資入門籌碼課：提高短線操作勝率,3600,5f8e3a347698f0649cf5da97,豹投資，專業投資人的邏輯整合大數據分析，成為多方投資策略的專業選股系統網站。\n不管在財務面...,投資理財,金融商品,股票,2022-01-25 12:11:38.459,<p>在台股市場做投資，最重要的就是看籌碼。</p><p>在這堂課裡，我們將用科學的方式，論...,1.了解三大法人與市場主力操作特性與思維 \n2.學會台股市場有許多客觀數據，提供你分析股市...,可以上網的裝置，例如筆記型電腦、平板、智慧型手機,特別適合初次接觸籌碼分析，或剛踏入股市想學習籌碼的新鮮人很友善～\n基本只要你對於股市、籌碼...,1. 沒有學過籌碼分析，對投資股票有興趣的新手\n2. 投資股票的時間還不滿一年\n3. 知...,NaN,left_only
1,5fe6fe2c5a5ba942b377c5ec,3,人物專訪怎麼寫？訪綱、採訪、寫作心法,2280,5fe6fdff5a5ba9064377c518,陳芷儀，耳草人內容工作室創辦人暨內容總監。天秤座 O 型（如果有人在意），政大傳播所畢。寫各...,人文,文學,文學,2022-01-24 12:08:59.923,<p>網站、雜誌、報紙⋯⋯，閱遍各類媒體，人物專訪絕對是不可或缺的元素。一篇專訪，可以幫助我...,1. 能規劃一場人物專訪\n2. 能擬定具水準的訪綱\n3. 在專訪現場的心理準備及臨場反應...,1. 電腦\n2. Google 雲端功能（建議但非必要）,1. 初學：完全沒有採訪經驗，想知道如何開始。\n2. 中階：有些採訪相關經驗，想持續進步。...,1. 對人物專訪或新聞採訪有興趣\n2. 想加強一對一、一對多對談的口語溝通技巧\n3. 想...,NaN,left_only
31,61666a458fc5c300073e6f60,5,放下酒譜！跟著 Mars 飛向浩瀚無垠調酒宇宙,3980,61551818a51e9e0007011eaa,【Mars】 為「2021年World Class世界頂尖調酒大賽」台灣冠軍。Mars自學習...,生活品味,烹飪料理與甜點,更多烹飪,2022-01-26 12:00:37.670,<blockquote>一堂超過 6 小時的全系列調酒課程，<br />5 道經驗淬煉的風味...,★ 5 道冠軍調酒師經驗淬煉的風味公式 ★ 學會超過百種排列組合的雞尾酒\n�� 快速學...,．只需要任何一款基酒跟一個結構，就可以調出數十杯以上的雞尾酒\n．糖漿，課程中也會教您自製簡...,．適合有基礎調酒概念者，可學會更獨具創意的雞尾酒以及概念發想\n．若為雞尾酒新手，建議從第一...,．適合曾多次製作過，但始終不知道怎麼調整細節讓調酒更好的人。\n．適合想嘗試做雞尾酒，但還沒...,NaN,left_only
26,6135374d94b8350007f7fe43,8,植物水彩繪 - 石斛蘭的觀察紀錄,2500,5fd30f93a79fe6299ab582f0,「植物藝術工作室』臉書粉專版主。雖然在城市長大，但更嚮往鄉下的生活。於是畫畫便是我療癒自我的...,藝術,繪畫與插畫,水彩,2022-01-18 12:00:26.742,"<img alt src=""https://images.api.hahow.in/imag...",1. 可以從眾家廠牌中挑選出適合植物水彩繪圖的工具\n2. 瞭解蘭花構造及相關知識\n3. ...,1. 圓頭水彩筆：建議筆毛要有彈性且不能太硬。\n2. 條狀或塊狀透明水彩顏料：學生級或是專...,喜歡植物，喜歡畫圖的學生都很適合。相信你不論是否已有植物或繪圖相關經驗，都可以從這門課吸收到...,1. 喜歡植物也想要把植物的美記錄下來的人\n2. 喜歡水彩也希望可以循序漸進進入水彩領域的...,NaN,left_only
13,60ed88d6b89d2300069ee963,9,新手開店0到1！餐飲創業成功必讀攻略術！,3980,60520446e928c7d51a1958d8,617行銷筆記，是為協助有心在商業行銷領域精進的人，準備的行銷觀點整理。\n \n617創立...,職場技能,創業,自主創業,2021-12-01 12:00:04.051,"<img alt src=""https://images.api.hahow.in/imag...",1.提高餐飲業的基礎知識及未來趨勢\n2.建立餐飲創業正確觀念，打好穩健經營基礎\n3.瞭解...,課程無需使用到任何工具/軟體，只要有一顆學習的心就好！,此課程主要設計給餐飲業「創業新手」、「經營一段時間但遇到瓶頸或找不到方法」的初學者\n不需具...,此課程較適合「初次創業餐飲店」的人：\n1.想開餐飲當老闆的人\n2.想開餐飲店卻還在籌備階...,NaN,left_only
2,5ff6aa28c5cbbcb694532eaa,10,插一盆花歌頌四季－我的自然感花藝創作法,2350,5cc6b925bc5432002078bd83,PM FLOWERS 創辦人、花藝設計師、花藝老師\nhttps://www.instagr...,"生活品味,藝術","壓力舒緩,更多生活品味,更多藝術","壓力舒緩,更多藝術",2021-11-30 12:00:02.723,"<img alt src=""https://images.api.hahow.in/imag...",1. 了解如何用更環保的方式插花，告別“花藝海綿”。\n2. 更細微地感受素材，了解他們在一...,必要工具：\n花藝剪刀、鐵絲雞網、劍山、黏土、膠帶與膠帶台、防水花瓶（透明、非透明皆可）、鐵...,只要對於花草充滿愛與熱誠就可以了！歡迎所有初學者喔,1. 想在家信手捻來享受插花美好的你。\n2. 已經成為花藝師或在花店工作，但想了解除了使...,NaN,left_only
25,6130495cd5d02a00071f2c3b,12,PChome 電商大學：給初學者的行銷入門課,499,6130492bd5d02a00071f2be5,走過21的本土電商PChome開課囉!希望藉由開創台灣電商藍圖的經驗，分享給對電商產業有興趣...,行銷,數位行銷,數位行銷,2022-01-05 12:01:22.835,"<p></p><img alt src=""https://images.api.hahow....",1.了解電商行銷的線上線下布局，如檔期策略、異業合作到話題擴散\n2.認識電商行銷在社群經營...,一顆對於電商產業有興趣及熱情、熱忱的心,初學者，歡迎完全不懂電商，但想要了解電商經營與行銷，但卻不知從何入門的大學生、社會新鮮人、轉...,1.\t大學在學生\n2.\t社會新鮮人\n3.\t對電商有興趣之創業者\n\n不適合：已經...,NaN,left_only
16,60fe7a7e006b74000621ce1f,13,雙語教學超前部署！互動式英語授課技巧,2680,5afa5a0ebb4174001e3fe107,CLN 致力於引領企業用外語佈局全球、教導學員以外語提升競爭力，讓客戶自在使用外語的同時，亦...,職場技能,更多職場技能,教學技巧,2022-01-04 12:00:02.459,<h4>&lt;試看單元搶先看&gt;</h4><blockquote>1-1 為什麼會開這...,(1) 陳述雙語教學與全英語教學的差異\n(2) 使用 CLIL (Content and ...,筆記本和一支筆，或是任何可以幫助你思考、實作紀錄的用品皆可,(1) 具備 CEFR B1 等級之英語能力分級測驗\n(2) 全民英檢中級或多益 650 ...,(1) 不分科目、年級，對雙語教學有熱忱的體制內老師、師培生\n(2) 不分程度、領域，想嘗...,NaN,left_only
28,613c4d77323c7f000694dd08,14,包租公/婆實戰攻略：隔套收租創造被動收入,3480,60ebb977fa79d90007aeaa3e,三年內成功打造數十間合法隔間套房，以自身成功經驗，分享給渴望成為包租公(婆)的你，打造被動收...,投資理財,金融商品,房地產,2022-01-11 12:00:33.870,"<img alt src=""https://images.api.hahow.in/imag...",1.\t在成千上萬房屋裡掌握挑選適合隔套的物件。\n2.\t在有限預算下達到最大租金效益。\...,無,這門課包含合法隔套收租的基礎觀念、看屋技巧、投報評估、招租實務，所以適合想成為包租公（婆）的...,1.\t想買房投資成為包租公（婆）。\n2.\t想增加被動收入卻不得門道者。\n3.\t家有...,NaN,left_only
10,60e2c36d2db6400007df9929,14,打造你的五官漂亮戰隊－堯蘭達高級臉精緻彩妝術,2000,60ace6f49c41f817c40a508c,一名專業彩妝師，也是一名變裝皇后表演者，我擁有商業彩妝與舞台彩妝的資歷，日常與表演經驗的穿插...,生活品味,"更多生活品味,護膚保養與化妝",護膚保養與化妝,2022-01-27 12:02:16.752,"<img alt src=""https://images.api.hahow.in/imag...",1. 學習加上反覆練習後，學生將會知道彩妝的細節步驟\n2. 依照自身條件調整為適合自己臉部...,1. 刷具：\n粉底刷／蜜粉刷／腮紅刷／修容刷／遮瑕刷／眼影暈染刷／眼影重點色刷／眼影小刷／...,適合初學者，或想精進細節美感之進階者,需要專業形象／社交／鏡頭需求／任何愛美之人士,NaN,left_only
14,60efd3a347b7d70006894784,14,毛孩肖像自己來｜6步驟掌握工筆畫貓訣竅,3000,60ebfac8ac2c110006186470,高義勝/ISHENGKAO1985生於台灣，嘉義。曾任教於國立高雄師範大學、國立台南大學及台...,藝術,繪畫與插畫,動物插畫,2021-12-09 12:00:02.467,"<img alt src=""https://images.api.hahow.in/imag...",➤ 可用毛筆畫出家中毛孩的模樣\n➤ 透過練習描繪，眼、手、腦要協調動作，可以鍛鍊想像力、創...,1.A3空白影印紙\n2.自動鉛筆、橡皮擦\n3.A3尺寸的礬宣或蟬衣宣(擇其一，市面上通常...,工筆畫的步驟是先用鉛筆製作線稿，修改到滿意後，再開始用毛筆描繪\n可以透過步驟畫出一定精細度...,1. 無基礎想畫畫的人\n2. 對水墨工筆感興趣的人\n3. 需要紓壓或培養專注力的人\n4...,NaN,left_only
17,6107cd6c3cc7a0000689c1c6,17,Knitting好好玩！自己織圍巾、披肩、羊毛帽,2480,60ee598667a1d3000629cdf2,May，專職玩毛線十多年，有一間靠近海的手染編織工作室，有植物，好咖啡，和機靈的狗朋友Oreo,手作,手作小物,手作小物,2022-01-26 12:51:56.434,"<img alt src=""https://images.api.hahow.in/imag...",�� 3 樣編織作品 -『波紋圍巾』、『三角披肩』、『雙色 pompom 帽』\n�� Kn...,這堂課的必要用具只有兩樣：「毛線」和「輪針」，超級簡單！\n�� 毛線：建議選擇天然羊毛線材...,�� 只要你喜歡動手做，對編織有熱情和好奇心，都歡迎加入。\n�� 初學的新朋友請放心參加，...,�� 想學棒針編織\n�� 喜歡編織，想要進步\n�� 想和大家一起織 3 樣作品\n�� ...,NaN,left_only
3,6039f9ad1f5b5b279b5183d5,18,業務力必備 - 高效達標的精準銷售術！,2490,6039f8415126b754b275e089,新加坡星億會計師事務所創辦人，2016年進入新加坡大華銀行(UOB)擔任客戶關係經理，201...,職場技能,"更多職場技能,職場溝通","更多職場技能,更多職場溝通",2021-11-30 12:02:18.013,"<img alt src=""https://images.api.hahow.in/imag...",1️⃣ 設置良好的「客戶篩選機制」，不再亂槍打鳥。\n2️⃣ 建立一套有計畫的「銷售流程」，...,不需要準備任何道具就可以上課。,本課程是針對想成為公司裡銷售冠軍（Top Sales）的業務所設計的課程，無需具備任何背景知...,剛進入或即將進入業務這行的人， 過去曾浪費很多時間在客戶上，終而不能簽約的業務，或是 已經從...,NaN,left_only
11,60e7f0598036260006b71683,21,主理人思維：服飾品牌創業入門課,1480,60aa25925f76bdfda327895a,【準心設計工作室】 『.67ARROW』自創潮流品牌，結合軍事元素與時事議題，自2017年起...,職場技能,"個人品牌經營,創業,更多職場技能","個人品牌經營,網路商店,自主創業",2021-12-16 12:00:03.501,"<ul><h4>課程緣起</h4></ul><img alt src=""https://im...",▲ 建立自己的品牌定位\n透過「目標市場設定」、「團隊能力及競爭對手能力評估」、「4P營銷策...,1. Ai（任何版本皆可）\n2. Google簡報（課程作業會附上連結��）\n3. Go...,1. Ai 繪圖軟體 基本功能操作 初階能力\n2. POWER POINT / EXCEL...,▲ 設計領域的學生或從業人員 \n▲ 準備自創品牌的新手\n▲ 已有自己的品牌 想做品牌轉型...,NaN,left_only
4,6056f8ceab70de413d98e723,22,Python 輿情應用趣：顧客樣貌分析攻略,2388,6056e11899b9a7d5ee54d472,臺灣行銷研究有限公司（TMR）所創建的【行銷資料科學團隊】 曾出版國內第一本的行銷資料科學書...,"程式,行銷","數位行銷,資料科學","Python 資料分析,數位行銷",2021-12-15 12:00:18.213,"<img alt src=""https://images.api.hahow.in/imag...",��技術面：網路爬蟲學習\n◆ 爬蟲技術基礎至實戰教學，建構爬蟲能力，強化爬蟲技巧。\n◆...,�� 一台穩定的電腦，不限 Mac/Windows/Linux 作業系統\n�� 需安裝 V...,��瞭解 Windows/Mac 電腦的基本操作。\n��具 Python 語法基礎者，帶您...,本課程歡迎有 Python 基礎者、資料分析初學者、行銷人、經理人、以及想從事資料分析工作的...,NaN,left_only
23,6125b83cdf147200070db995,86,李昆霖品牌實戰十講：感召人心的品牌方程式,3980,6125b7acb813fb0006f3c9cf,網路上人稱腦闆。\n征服法國的台灣面膜——提提研的創辦人，還開了一間全台灣最美的漫畫店BOO...,"職場技能,行銷","個人品牌經營,創業,更多職場技能,更多行銷","個人品牌經營,更多創業,更多行銷",2022-01-12 11:58:59.057,<blockquote>試看單元：搶先體驗課程第二講「品牌的市場定位」</blockquot...,在自己的產品、內容、工作上運用品牌策略，跳脫削價競爭、提升品牌價值。\n用品牌思維規劃「市場...,可觀看線上課程影片的電腦、平板或手機,無需特殊背景知識,只要你有想要推廣的產品、內容或理念，無論屬於哪個產業，這堂課都能幫助你打造感召人心的品牌。,NaN,left_only
6,6083734d17b1e70d08fd3ca6,90,空間美學大改造｜善用軟裝佈置夢幻居家生活,2280,607d34bf91cb6254cdcb76e5,原本在紐約知名服飾品牌行銷擔任 PM，回到台灣後意外愛上房產，從此沉浸在房產的世界,生活品味,居家,居家,2021-12-14 11:59:56.675,"<img alt src=""https://images.api.hahow.in/imag...",1. 學會如何找到合適自己風格的軟裝品\n2. 學會找到 CP 值最高的軟裝擺設品\n3. ...,- 選擇一個計算機\n- 選擇一個可以上網的設備\n- 選擇一個適合你的筆記方式,1. 想用小資金提升居住品質與美感的你\n2. 想提升居家空間感的你\n3. 想運用佈置將...,1. 想要提升空間美學意識者\n2. 想要提升對房屋裝潢美學概念者\n3. 希望能透過美化空...,NaN,left_only
15,60fcc2932b90ea00074c4a16,93,面向市場的自媒體說故事法則：心態與思考篇,2600,5d03d1348834eb00227190d0,Edo (艾德導演)\n“如果影像回歸至最原始的初衷，其實就是單純的 紀錄”\nEdo為台灣...,攝影,動態攝影,動態攝影,2021-12-07 12:00:25.952,"<img alt src=""https://images.api.hahow.in/imag...",1. 發掘出一套屬於自己的思考模式，開發出一個影片主題，並學會規劃與設計腳本架構\n2. 了...,你需要紙跟筆或是可以做筆記的電腦，想學習與輕鬆舒服的心情。,這堂課程我們將 Focus 在學習思考與創造，不管初學或是進階者都適合。,1. 我是新手，想了解影像創作或想嘗試踏入自媒體的朋友\n2. 已經是自媒體創作者，想更了解...,NaN,left_only
5,605ca63e3cd943ce48dc5daa,110,NFT 加密藝術｜買幣、發行、交易一次上手！,2490,605ca564acf40e349d0ad43a,新媒體藝術家，目前居住於LA，芒果飯忠誠信徒。畢業於美國聖荷西大學數位媒體藝術研究所。\nu...,"投資理財,程式,藝術","區塊鏈,更多藝術,金融商品","更多藝術,虛擬貨幣",2021-12-16 12:40:40.923,<blockquote>加碼活動來囉！</blockquote><pre>2022-02-2...,．認識什麼是加密藝術／NFT\n．設定自己的第一個加密貨幣錢包（使用 MetaMask & ...,．銀行帳戶或是信用卡\n．身分認證文件（例如：身分證、護照）\n．當地手機號碼（例如：台灣手...,這堂課程適合對加密貨幣／加密藝術沒有任何基礎的同學，將會循序漸進帶你學習並進行實際的操作，適...,．初心者\n沒有任何相關知識的初心者，大概聽過比特幣或區塊鏈。想認識區塊鏈在 NFT 的應用...,NaN,left_only
9,60dd6d80638ed00aa99b5556,111,Excel 新手入門必修課：從 0 開始,990,5e2a9788e3832b002472399a,我是Tina Wu ���� 在Hahow開設《台科EMBA年年爆滿的一門 Word課》《職...,"程式,職場技能","效率提升,文書處理,更多職場技能,資料彙整,資料科學","Excel,效率提升,更多職場技能,資料彙整",2021-12-01 13:24:46.186,<blockquote><b>此堂課為舊的 Excel 入門課之全新改版～<br />已上過...,1. 更扎實的擁有 Excel 操作觀念\n2. 有效及快速整理大量數據及資料分析的能力\n...,1. 一台 Windows 或 Mac 的電腦+滑鼠（建議準備滑鼠）\n2. 電腦需要安裝 ...,1. 瞭解 Windows/Mac 的電腦基本操作，並知道怎麼將 Word、Excel 及 ...,1. 為踏入職場做準備的學生\n2. 職場上需要處理數據的上班族\n3. 想提升個人競爭力的...,NaN,left_only
7,60b49206c0bb3056c3a6ee52,134,買房請注意，新成屋中古屋首購攻略,2980,60654b40e28e58a36d02ebbb,擁有不動產經驗約10年左右，辦過200場以上講座分享，共累積1000位以上學員，協助100...,投資理財,金融商品,房地產,2021-12-14 12:01:29.036,<p>本課程將於 2022/06/15 調整售價至 2980 元，請有購課需求的同學留意售價...,●了解如何選擇房仲，並看懂房仲的操作手法\n●評估房子的保值性，並看懂不動產說明書及謄本\n...,無,這門課針對買房新手設計，不需要特別的背景以及專業，只要對於成屋(包括新成屋、中古屋等)買賣有...,●近期想要買成屋的人\n●正在看屋的人\n●想要換成屋的人\n●想了解不動產的新手\n●購屋...,NaN,left_only
20,611f5d074b76af0007c24d7e,228,風格藝術 設計上線 - 用 PS、AI 做吸睛視覺設計,3200,5bdaa4f20e5a400020262571,電腦技能基金會(CSF)深耕認證領域三十年，發展各項能力認證，已成為全國最大、最具公信力的認...,"藝術,設計","平面設計,設計理論,電腦繪圖","Illustrator/以拉,photoshop,設計理論",2021-12-06 12:00:21.692,"<img alt src=""https://images.api.hahow.in/imag...",學到：近年國際流行的平面設計設計風格\n1. 資源搜尋能力\n2. 軟體操作能力...,1. 須具備基本電腦操作能力、需備有 AI 與 PS，版本為 CC 以上的軟體。\n2....,無基礎或是有基礎的喜愛平面設計的人。,1. 想要累積作品集的人。\n2. 有興趣想做出好看的作品的人。\n3. 想靠自...,NaN,left_only
18,61161afbbeafad00060b4503,256,高質感 PPT 設計：不用 PS、AI 的設計指南,2800,572abc76d60bb3090091cc9c,我是「簡報初學者」的創辦人Allan，同時也是中國的視覺設計團隊AbleSlide的內容總監...,"職場技能,設計","平面設計,文書處理,職場溝通","PowerPoint,更多平面設計工具,簡報技巧",2021-11-15 14:03:28.204,"<p></p><img alt src=""https://images.api.hahow....",1. 提高簡報力：熟練使用 PPT 高效操作技巧，提高簡報製作效率。\n\n2. 升級設計力...,這門課有很多案例實作，使用軟體為 PowerPoint。版本建議至少是 PowerPoint...,這是一門給初學者的 PPT 設計課，只要對簡報軟體 PowerPoint 的使用有基本認識，...,1. 想提升簡報質感的上班族\n2. 想自製貼文配圖的社群小編\n3. 想打造個人品牌的自媒體人,NaN,left_only
22,61237ed5df69e30006dbfff7,277,曾寶儀——從心開始的溝通術,1900,61237e7fbe9b6800064d404e,以說話為工作，自詡是個暢通的管道的人,"生活品味,職場技能","心靈成長與教育,更多生活品味,職場溝通","心靈成長與教育,更多職場溝通",2021-10-08 11:57:29.416,"<img alt src=""https://images.api.hahow.in/imag...",# 找到自己溝通風格的方法\n從「認識自己是怎樣的溝通者」開始，\n你是什麼、在乎什麼，就會...,電腦、平板或手機，任一你方便播放課程影片的工具,無需特殊背景知識,希望找到力量真誠表達、療癒重要關係、更加認識自己的你,NaN,left_only
24,612f7b671bf9240007a68ad4,277,做伙來講台語！阿華師的日常台語會話課,1490,612f774007604b0007d085e6,5歲了後毋捌閣講台語。\n交大光電畢業去澳洲做台勞做一冬。\n26歲蹛客庄，學塗礱、學客話、...,語言,更多語言,更多語言,2021-12-21 12:07:59.122,"<img alt src=""https://images.api.hahow.in/imag...",各種生活情景有才調全台語對話三分鐘；會曉用台語問台語； 知影台語中文句型文法無仝 ê 所在。...,建議手機仔愛先安台語輸入法：Lohankha / PhahTaigi\n（建議手機可以先下載...,基礎愛有：民視三立台語八點檔無看字幕八成以上聽有。\n上好是：課前先看過「台南妹仔教你講台語...,適合：慣勢講華語，台語聽有、煞無啥會曉講，見講 to 講出「華語氣ê台語」chit 款 ê ...,NaN,left_only
12,60ed57916444da00061af44d,299,平面設計概論與流程：李君慈的視覺基礎課,2500,60ed575d8b4cd40006fb2ca1,平面室的設計總監 、LADYBUG創辦人，設計範疇從書籍裝幀、品牌視覺規劃、影像視覺字體字幕...,"藝術,設計","平面設計,設計理論,電腦繪圖","Illustrator/以拉,photoshop,設計理論",2021-12-08 12:00:04.834,"<img alt src=""https://images.api.hahow.in/imag...",- 從設計師角度思考與使用設計流程，獨立有效地完成視覺編排設計\n- 明白設計前期的準備事項...,這門課比較偏向概念上的實際應用教學，所以無需先有軟體基礎。\n想要更成熟的實際運用可再去研究...,主要教學會著重在設計初階基礎，適合基礎不穩固，但會使用軟體，卻苦無入門方式的朋友！\n亦或平...,初進職場設計師、有在做編排設計的學生、對視覺設計感興趣的朋友,NaN,left_only
29,6155cda6d425f500065f5c96,313,動態設計思維，柏尹帶你培養品牌動畫鑑賞力,0,5f7c1de062ad22eb607a1a00,Today at Apple 是由 Apple 精心設計的免費課程，透過攝影、藝術與設計、影...,設計,動態設計,"動態設計思維,更多動態設計工具",2021-11-10 12:09:15.489,"<img alt src=""https://images.api.hahow.in/imag...",可以更能理解動態設計的製作心法過程，並看得懂動畫的組成因素！,你可以準備一台可以觀看影片的電腦，以及培養想要了解動畫的心情～\n如果你想要操作老師於課程中...,無，適合任何對於動態設計有興趣的族群,對於動態設計有工作需求的族群，以及純粹想了解動態設計編排的大眾,NaN,left_only
8,60c84de9eb75ca46e0c25e85,435,我想離婚怎麼辦：兒福聯盟的離婚規劃課,0,60c06ac239ddd723beb1bdd8,1991年從修訂兒少福利法開始，歷經三十年的時間，兒福聯盟已經推展超過25種服務項目。與時俱...,生活品味,"心靈成長與教育,更多生活品味",心靈成長與教育,2021-10-25 12:00:10.120,"<p></p><img alt src=""https://images.api.hahow....",1.可以學到如何好好的檢視自己的婚姻狀態。\n2.可以學到如何好好的離婚並能好好與孩子溝通及...,紙、筆等筆記工具，和一顆平和開放的心。,無程度限制。,1.感覺自己的婚姻遇到瓶頸的人。\n2.已經在離婚狀態中，想更知道如何處理的人。\n3.正在...,NaN,left_only
30,6156a77fdf426a0007cc5fe1,435,建立個人品牌視覺：諾米帶你上手風格再造,0,5f7c1de062ad22eb607a1a00,Today at Apple 是由 Apple 精心設計的免費課程，透過攝影、藝術與設計、影...,"職場技能,藝術","個人品牌經營,更多職場技能,電腦繪圖","Procreate,個人品牌經營",2021-11-10 12:09:22.599,"<img alt src=""https://images.api.hahow.in/imag...",可以更加了解個人風格塑造是如何進行，並用簡單的方式上手,可以準備筆記本，記錄下來你的學習心得，如果你想實際練習操作老師於課程中所提的繪圖方式，請準備...,適合一般大眾，不需背景知識,想要進行個人品牌創造、或是建立品牌風格的大眾！,NaN,left_only
27,61381a3f33a3960006df1eb3,926,RyuuuTV看動漫看日劇，零到N4道地說日文,3500,60c30c3c207fba38ec73df37,大家好，我們是 Ryu 和 Yuma，是一個住在日本的馬來西亞男生和日本老婆夫婦檔經營的學日...,語言,日文,日文口說,2022-01-17 12:00:08.970,<blockquote><b>2022 課程更新計畫��：新增 N5、N4 日檢重要文法 3...,- 學會從基礎的五十音到日文 N4 程度的日文文法\n- 認識生活、旅遊、流行文化（動漫畫、...,只要有電腦、平板或手機，可以用來看課程就 ok！,無，只要帶著輕鬆的心情一起加入課程就可以囉！,- 想學會日文，看懂日常在追的動漫畫、日劇或 J-pop、歌曲\n- 想透過日文更深入了解道...,NaN,left_only
21,611f7d91bd122100071f2926,1066,可愛先決！跟著叮咚拍出日雜般的家庭寫真,2999,60d98eb091602a2cb2c86710,Dingdong Lee\n攝影師\n擅長在生活時光中自然擷取，為平凡的日常拍下充滿柔軟的瞬...,攝影,影像創作,影像創作,2021-12-13 13:33:27.796,<blockquote><b>課程加量不加價！<br />沒有器材門檻，把日常拍成日雜，手機...,重新喜歡上攝影，並瞭解攝影師叮咚拍攝的所有技巧與安排，包括光線佈局、取景角度、捕捉瞬間、配色...,擁有拍照功能的手機、數位相機,無需基礎，歡迎所有攝影初學者、或想記錄家庭寫真的人,1. 想為所愛之人留下值得回憶的影像\n2. 想拍出充滿日雜質感的攝影作品\n3. 對於攝影...,NaN,left_only

In [205]:
t = data['val_seen'].set_index("user_id").course_id.apply(lambda s: s.split()).explode().to_frame("course_id")

In [20]:
user_course_dict = data['train'].set_index("user_id")["course_id"].to_dict()

In [26]:
df = train_df["course_id"].value_counts().to_frame("n")

In [34]:
df = df.reset_index().rename(columns={"index": "course_id"})

In [35]:
df_ = data['val_seen'].course_id.apply(lambda s: s.split()).explode().to_frame("course_id")
for i in range(100, 2001, 50):
    popular_course = df.query(f"n > {i}")
    l = len(df_.merge(popular_course, on=["course_id"], how="inner"))
    print(i, len(popular_course), l, l/len(df_))

100 235 9428 0.5291575461637762
150 161 8393 0.47106695852275915
200 123 7743 0.4345849469607678
250 104 7180 0.4029859123309199
300 80 6388 0.3585339843969243
350 72 6202 0.34809451647303136
400 61 5796 0.3253072907896952
450 53 5421 0.3042599764270079
500 50 5305 0.2977493405174833
550 48 5195 0.2915754616377617
600 45 5086 0.2854577089296739
650 40 4974 0.2791715777066846
700 37 4844 0.27187517539428635
750 36 4785 0.26856373126789024
800 36 4785 0.26856373126789024
850 36 4785 0.26856373126789024
900 33 4697 0.2636246281641129
950 31 4557 0.2557669641353763
1000 30 4500 0.25256777235224787
1050 27 4329 0.24297019700286243
1100 23 4204 0.23595442554863333
1150 23 4204 0.23595442554863333
1200 22 4187 0.23500028063085818
1250 21 4051 0.2273671212886569
1300 20 4003 0.22467306505023293
1350 20 4003 0.22467306505023293
1400 20 4003 0.22467306505023293
1450 17 3680 0.20654431161250492
1500 14 3532 0.19823763821069765
1550 12 3344 0.18768591794353706
1600 12 3344 0.18768591794353706
1650 12 3344 0.18768591794353706
1700 12 3344 0.18768591794353706
1750 12 3344 0.18768591794353706
1800 11 3240 0.18184879609361845
1850 11 3240 0.18184879609361845
1900 11 3240 0.18184879609361845
1950 10 3202 0.1797160015715328
2000 10 3202 0.1797160015715328

In [42]:
pd.Timestamp('2021-12-21')

Timestamp('2021-12-21 00:00:00')

In [60]:
df = data['train'].explode("course_id")['course_id'].value_counts().to_frame("n").reset_index().rename(columns={"index": "course_id"})

In [65]:
data['courses'].query("n > 0")['course_published_at_local'].max()

Timestamp('2021-11-29 12:00:14.527000')

In [69]:
len(data['courses'])

664

In [67]:
data['courses'].query("course_published_at_local >= @pd.Timestamp('2021-11-29')")

,course_id,course_name,course_price,teacher_id,teacher_intro,groups,sub_groups,topics,course_published_at_local,description,will_learn,required_tools,recommended_background,target_group,n
662,60c2e123dcc8c38df47514c1,雙語教育必學的核心素養－用英文學知識,2000,60c2e0dcc121046b1958594d,新視紀，網羅各專業領域的鬼才，包含業界各個領域，甚至教育界的菁英，一同不藏私的與大家分享一身...,"生活品味,語言","更多生活品味,英文,親子教育","英文,親子教育",2021-11-29 11:51:11.069,"<img alt src=""https://images.api.hahow.in/imag...",● 英文、學科知識、核心素養能力一併提升\n● 提升靈活應用英語的能力\n● 提升獨立思考、...,觀看線上課程的電腦設備、方便做筆記的紙筆。,此本課程不需先備知識，只要有興趣參加即可。\n,適用對象一：國小學生（英文程度小學二年級以上）\n此門課程針對『108 課綱的核心素養』所設...,2
663,5f55fb39b34335d28416bd0c,音樂人必學，編曲製作心法,2199,5ab61884dc2ab6001e266e34,上方房子↑是 ig 可以訊息！\n\nMusic Creator / Youtuber\n—...,音樂,音樂創作,作曲和編曲,2021-11-29 12:00:14.527,"<h4>課程緣起</h4><img alt src=""https://images.api....",1. 將強化本身關於音樂的編曲概念。 \n2.你對任何曲風的音樂，都會有一定的編曲掌握能力。,1.筆記本／數位筆記\n2.電腦／平板／手機（能音樂製作的硬體工具）\n2.DAW 音樂製作...,本堂為中階課程，需有基礎的音樂製作軟體的經驗，但不限軟體廠牌種類，而課程的初衷是希望降低編曲...,因為科技進步的力量，使我們音樂創造方式大大改變。\n1. 剛接觸了數位音樂後但對編曲懵懂的同...,2

In [38]:
data['val_seen'].course_id.apply(lambda s: s.split()).explode()

0       5b61928a8011d1001e356102
1       559e49185850311000fca504
2       60ddc3ca06259d00064c7f17
2       60aeac37bca91777bf5bb114
2       60c84de9eb75ca46e0c25e85
                  ...
7743    601d03e07e6747ef11bba066
7744    5ca17cd572a72f002150ed9d
7745    61381a3f33a3960006df1eb3
7746    6156a77fdf426a0007cc5fe1
7747    61381a3f33a3960006df1eb3
Name: course_id, Length: 17817, dtype: object

In [83]:
data['val_seen'].course_id.apply(lambda s: s.split()).explode().to_frame("course_id").merge(df, on=["course_id"], how="inner")

                      course_id   n
0      5b61928a8011d1001e356102  74
1      5b61928a8011d1001e356102  74
2      5b61928a8011d1001e356102  74
3      5b61928a8011d1001e356102  74
4      5b61928a8011d1001e356102  74
...                         ...  ..
12152  5e9e7c78735b0146e5cbae8b  11
12153  586a2519f108e00800c26e61   3
12154  5e4612145b02f600245ab028  21
12155  5f5052c05a021d2bda2761da  32
12156  582548cf5910c807008267b4   7

[12157 rows x 2 columns]

In [58]:
len(courses)

17817

In [15]:
data['courses'].query("course_id == '5f59ff38f24eac1485f8097f'")

,course_id,course_name,course_price,teacher_id,teacher_intro,groups,sub_groups,topics,course_published_at_local,description,will_learn,required_tools,recommended_background,target_group
518,5f59ff38f24eac1485f8097f,掌握關鍵數據，黃金、原油投資高勝率全攻略,3600,5a93c4d418b67a001ee39779,「MacroMicro 財經M平方」致力於整合全球總經數據、協助投資人運用經濟指標找到投資方...,投資理財,"投資觀念,金融商品","ETF,投資觀念",2020-12-02 12:00:06.708,<blockquote><b>歡迎登入 Hahow 會員，點選播放視窗右邊的「試看單元」體驗...,原油\n・從 OPEC+及中東地緣政治，看懂哪些國際角力是油價關鍵、哪些又是雜訊 \n・理解...,1. 可以上網的電腦或平板 \n2. 紙筆或是任何可以幫助您紀錄的工具\n3. 推薦輔助工具...,1. 投資商品、投資操作相關名詞的認識\n如：槓桿型 ETF、ETF 折溢價、高收益債券殖利...,我們認為每位投資人都應該了解全球經濟運行， 如果你希望將投資商品觸及全球市場，或者單純想看...

In [38]:
data['val_unseen'].merge(data['train'], on=['user_id'], how='left').dropna()

Empty DataFrame
Columns: [user_id, course_id_x, course_id_y]
Index: []